scss compile, expanded for dev
bootscore/bootscore pull request #279
Opened 2022-10-06 05:49 UTC by sean-au

2022-10-06 05:50 UTC, sean-au commented
ouptuts explanded SCSS in dev env
dev env now includes development and local
scss error message supressed in production (only basic message shown)

2022-10-06 14:34 UTC, justinkruit requested changes
If you could change these things, then I think it's fine for approval.

2022-10-06 14:34 UTC, justinkruit commented on inc/scss-compiler.php
> +      wp_die('<b>SCSS ERROR!</b>');
A nicer error message would be better.
```suggestion
      wp_die('Something went wrong with the SCSS compiler.');
```

2022-10-06 14:34 UTC, justinkruit commented on inc/scss-compiler.php
> +    } else { // supress error message for production
The comment isn't really necessary.
```suggestion
    } else {
```

2022-10-08 01:50 UTC, sean-au commented
Hi @justinkruit I pushed the requested changes

2022-10-13 17:42 UTC, justinkruit approved these changes
All looks good now 👍

2022-10-13 17:42 UTC, merged