Create CODE_OF_CONDUCT.md
bootscore/bootscore pull request #611
Opened 2023-10-23 10:23 UTC by crftwrk

I think having a Code of conduct is the common standard.

2023-10-27 14:16 UTC, justinkruit requested changes

2023-10-27 14:16 UTC, justinkruit commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
We may need to change this 😂

2023-10-27 16:54 UTC, crftwrk commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
Oops... sorry, done ;-)

2023-11-10 14:32 UTC, justinkruit approved these changes

2023-11-10 14:33 UTC, merged