[Fix] Mini Cart Currency Symbol Position
bootscore/bootscore pull request #716
Opened 2024-03-02 19:13 UTC by anisur2805

Hey @crftwrk,
I have checked this currency position, and it is not updated according to woo-commerce backend settings without product quantity update or added to the cart. I have RnD about it and found a notice in the admin panel. I have checked more than 3/4 industry's top themes which have done the same way to update their quantity. As far as my RnD it's a default behaviour of WooCommerce. 

Please share your thoughts.

![image](https://github.com/bootscore/bootscore/assets/11018986/a2e89e21-7c89-4c3b-80a2-f1ef616ebb72)

2024-03-02 19:43 UTC, justinkruit commented
This is not the correct way to render prices in WooCommerce. The function wc_price does this formatting for you, and we should actually use that.

2024-03-02 19:55 UTC, justinkruit requested changes
Use wc_price to format the price (see above comment).

2024-03-04 11:18 UTC, crftwrk commented
@justinkruit What's wrong here? Works fine? Is this something what we can change later by ourself easily?

2024-03-04 11:21 UTC, justinkruit commented
> Is this something what we can change later by ourself easily?

We can, but imo we should fix it before the v6 release.

> What's wrong here? Works fine?

It works, but it's not the correct way to render a price in Woocommerce. Here it's manually built, while woocommerce has a function for this built in.

2024-03-04 11:31 UTC, crftwrk commented
@justinkruit can you provide a quick code example how it should look like?

2024-03-04 11:37 UTC, anisur2805 commented
@justinkruit here is the explanatory video I have recorded a [video](https://www.awesomescreenshot.com/video/25458233?key=c422e0f320100acb89a98649f750113c) for you. Please have a look. And I will fix the price display code as you have suggested me within very soon. 

Thank you.

2024-03-04 12:06 UTC, closed without merging